version: '3.8'
services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=open-health
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    environment:
      - DATABASE_URL=postgres://postgres:mysecretpassword@db:5432/open-health
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  postgres_data:
